---
title: "Lab2_1_SBUCD"
output: html_document
---

## like vectors, data matrices are restricted to data of the same type

## practice
```{r}
spring_1 <- c(36.25, 35.40, 35.30)
spring_2 <- c(35.15, 35.35, 33.35)
spring_3 <- c(30.70, 29.65, 29.20)
spring_4 <- c(39.70, 40.05, 38.65)
spring_5 <- c(31.85, 31.40, 29.30)
spring_6 <- c(30.20, 30.65, 29.75)
spring_7 <- c(32.90, 32.50, 32.80)
spring_8 <- c(36.80, 36.45, 33.15)
```

```{r}
springs <- c(spring_1, spring_2, spring_3, spring_4, spring_5, spring_6, spring_7, spring_8)
springs_matrix <-matrix(springs, nrow=8, byrow = T)
```

```{r}
scientists <- c("Jill","Steve", "Susan")
springs <- c("Blubell Spring", "Opal Spring", "Riverside Spring", "Too Hot Spring", "Mystery Spring", "Emerald Spring", "Black Spring", "Pearl Spring")
```

```{r}
colnames(springs_matrix) <- scientists
rownames(springs_matrix) <- springs
```

```{r}
springs_matrix
```

```{r}
mean_vector <- rowMeans(springs_matrix)
mean_vector
```

```{r}
springs_matrix2 <- cbind(springs_matrix, mean_vector)
scientists2 <- c("Jill", "Steve", "Susan", "Mean")
colnames(springs_matrix2) <- scientists2
springs_matrix2
```

## what we worked on: objects, classes of data, ways data an be organized, practice with vectors (strings of data), organize vectors into data matrices, have to give R dimension to make it a matrix
## dataframe > matrix > vector